// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywnhywhkodcxhumlzwxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bmh5d2hrb2RjeGh1bWx6d3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTIxNDAsImV4cCI6MjA2MzU2ODE0MH0.vylGj_y1HMiUtKMu5iGgGAaVar4P266meZMCF3N2V3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);